import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en">
        <body className={inter.className}>
          <link
            href="https://unpkg.com/swiper/swiper-bundle.min.css"
            rel="stylesheet"
          />
          <Navbar />
          {children}
          <Footer />
          <script
            src="https://kit.fontawesome.com/4647efb575.js"
            crossorigin="anonymous"
          />
          <script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
        </body>
      </html>
    </>
  );
}
